### ISSUE TITLE
Add missing ", The" to titles

### ISSUE THREAD

**Issue by nhjm449** [sugrocks/cn-schedule#94]
For CN-sourced series/episode titles:

Any time there is a space at the end of a name, it should be replaced with ", The".

```javascript
seriesOrEpisodeTitle.replace(/ ($|\/)/g, ", The$1")
```

Ex.
Multi-element episode title: "Kids /Fan " → "Kids, The/Fan, The"
Movie title: "Tom and Jerry: Fast and the Furry " → "Tom and Jerry: Fast and the Furry, The"
Series title: "Cleveland Show " → "Cleveland Show, The"

Technically this should be done at the API level, ~~but I don't see a public repo for that. :wink:~~ (Edit: I found where the API code is, but I don't really want to create a second issue for this.)

Knowledge source: Years of dealing with this, etc.

**Comment by mkody** [comment]
I noticed that on some titles but it didn't look like a big problem to me.
Will fix that later today, thanks. :+1:
